
DEBUG = true
DISPLAY = true
logEdexToFile = false
disableEdexTimer = false

function onCreate()
	--OFP:showPopup("level", "initialized")
	
	OFP:setAIConfigPropertyValue("Medic.AllieCheckRadius", "60.f")
	OFP:setAIConfigPropertyValue("Medic.MaximumHealDistancePlayer", "200.f")
	OFP:setAIConfigPropertyValue("Medic.MaximumHealDistanceAI", "100.f")
	OFP:setAIConfigPropertyValue("Medic.CreateNoHealingAreaOnCommandFailure", "true")
	OFP:setAIConfigPropertyValue("Medic.NoHealingAreaRadius", "30.f")
	OFP:setAIConfigPropertyValue("Medic.InitialNoHealingAreaCooldownTime", "2000")
	OFP:setAIConfigPropertyValue("Medic.NoHealingAreaCooldownTime", "8000")
	OFP:setAIConfigPropertyValue("Medic.MedicIntervalTime", "0")
	OFP:setAIConfigPropertyValue("PathFinding.LandscapeHeuristicBias", "2.0")
	OFP:setAIConfigPropertyValue("ConflictGroup.Overlap", "50")
	OFP:setAIConfigPropertyValue("Strength.UNIT_STATIC", "60")
	OFP:setAIConfigPropertyValue("Strength.UNIT_BOAT", "90")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AIRCRAFT", "80")
	OFP:setAIConfigPropertyValue("Strength.UNIT_HELICOPTER", "110")
	OFP:setAIConfigPropertyValue("Strength.UNIT_HEAVYTRACK", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_APCTRACK", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_APCWHEEL", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_ARMTRACK", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_ARMWHEEL", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AMPHIBARMTRACK", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AMPHIBAPCTRACK", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AMPHIBARMWHEEL", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AMPHIBAPCWHEEL", "100")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SOFTHUMVEE", "70")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SOFTFUELTRUCK", "60")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SOFTAMMOTRUCK", "60")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SOFTTRUCK", "70")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SOFTJEEP", "70")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFSNIPER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFAASPECIALIST", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFMORTARGUNNER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFFWDOBSERVER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFENGINEER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFMEDIC", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFGRENADIER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFMACHINEGUNNER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFRIFLEMAN", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SFLEADER", "10")
	OFP:setAIConfigPropertyValue("Strength.UNIT_JETPILOT", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_DOORGUNNER", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_HELICOPTERPILOT", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_TRUCKCREW", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AFVCREWMAN", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AFVCOMMANDER", "3")
	OFP:setAIConfigPropertyValue("Strength.UNIT_FWDOBSERVER", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_ENGINEER", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SNIPER", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_JAVELINGUNNER", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_AASPECIALIST", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_MORTARGUNNER", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_ATSPECIALIST", "8")
	OFP:setAIConfigPropertyValue("Strength.UNIT_MACHINEGUNNER", "7")
	OFP:setAIConfigPropertyValue("Strength.UNIT_MEDIC", "4")
	OFP:setAIConfigPropertyValue("Strength.UNIT_GRENADIER", "6")
	OFP:setAIConfigPropertyValue("Strength.UNIT_RIFLEMAN", "6")
	OFP:setAIConfigPropertyValue("Strength.UNIT_FTLEADER", "6")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SQUADLEADER", "6")
	OFP:setAIConfigPropertyValue("Strength.UNIT_PLATOONLEADER", "6")
	OFP:setAIConfigPropertyValue("Strength.UNIT_SENIOROFFICER", "6")
	OFP:setAIConfigPropertyValue("WeaponUsage.Grenade.FragMaxRange", "50.0")
	OFP:setAIConfigPropertyValue("WeaponUsage.Grenade.FragMinRange", "15.0")
	OFP:setAIConfigPropertyValue("SoldierMedicSensor.RunAwayFailDistance", "60.0")
	OFP:setAIConfigPropertyValue("Doctrine.Timeout", "90")
	OFP:setAIConfigPropertyValue("TargetSensor.LongRangeDistance", "450.0")
	OFP:setAIConfigPropertyValue("TargetSensor.MidRangeDistance", "100.0")
	OFP:setAIConfigPropertyValue("Distances.EchelonShareSuspectedThreatRadius", "60.0")
	OFP:setAIConfigPropertyValue("BodyController.TurnToLookHints", "true")
	OFP:setAIConfigPropertyValue("HearingSensor.CriticalDetectionDistance", "30")
	OFP:setAIConfigPropertyValue("HearingSensor.MaxRandomLookAtMilliseconds", "12000")
	OFP:setAIConfigPropertyValue("HearingSensor.MinRandomLookAtMilliseconds", "8000")
	OFP:setAIConfigPropertyValue("HearingSensor.ScoreCutoff", "2")
	OFP:setAIConfigPropertyValue("HearingSensor.ScoreBaseMultiplier", "28")
	OFP:setAIConfigPropertyValue("Feedback.EnemyDownFeedbackRequestPool", "16")
	OFP:setAIConfigPropertyValue("Feedback.DecoratorRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.GrenadeWarningFeedbackRequestPool", "4")
	OFP:setAIConfigPropertyValue("Feedback.CorpseReportRequestPool", "4")
	OFP:setAIConfigPropertyValue("Feedback.PlaceholderOffboardSupportRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.HQOrderFeedbackRequestPool", "4")
	OFP:setAIConfigPropertyValue("Feedback.VehicleTargetAcknowledgeFeedbackRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.VehicleTargetOrderFeedbackRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.TargetOrderFeedbackRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.GenericOrderFeedbackRequestPool", "45")
	OFP:setAIConfigPropertyValue("Feedback.GridRefOrderFeedbackRequestPool", "32")
	OFP:setAIConfigPropertyValue("Feedback.ScriptSpeechRequestPool", "16")
	OFP:setAIConfigPropertyValue("Feedback.TargetSpottedFeedbackRequestPool", "32")
	OFP:setAIConfigPropertyValue("Feedback.SoldierDownFeedbackRequestPool", "8")
	OFP:setAIConfigPropertyValue("Feedback.InjuryFeedbackRequestPool", "16")
	OFP:setAIConfigPropertyValue("Feedback.SimpleFeedbackRequestPool", "32")
	OFP:setAIConfigPropertyValue("Feedback.SpamRequestLifetimeMS", "500")
	OFP:setAIConfigPropertyValue("Feedback.SpamRequestHistory", "30")
	OFP:setAIConfigPropertyValue("Feedback.GrantedRequestLifetimeMS", "5000")
	OFP:setAIConfigPropertyValue("Feedback.GrantedRequestHistory", "30")
	OFP:setAIConfigPropertyValue("LineOfFireSensor.RangeLimitModifier", "1.0")
	OFP:setAIConfigPropertyValue("LineOfFireSensor.LineOfFireObscuredTime", "5000")
	OFP:setAIConfigPropertyValue("TargetSelectionController.UpdateInterval", "1000")
	OFP:setAIConfigPropertyValue("TargetSelectionController.DangerZoneRadius", "30")
	OFP:setAIConfigPropertyValue("TargetSelectionController.SuppressScoreValue", "400")
	OFP:setAIConfigPropertyValue("TargetSelectionController.SwapScoreBuffer", "10")
	OFP:setAIConfigPropertyValue("TargetSelectionController.RejectionThreshold", "-400")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.EStanding", "1.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.ECrouching", "0.85")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.EProne", "0.5")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.Boat", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.Aircraft", "4.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.Helicopter", "4.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.HeavyTrackedVehicle", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.APCTrack", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.APCWheel", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.AmphibArmouredTrack", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.AmphibAPCTrack", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.AmphibArmouredWheel", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.AmphibAPCWheel", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.SoftHumvee", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.SoftFuelTruck", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.SoftAmmoTruck", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.SoftTruck", "3.0")
	OFP:setAIConfigPropertyValue("SightSensorModifiers.SoftJeep", "3.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.NoMorale", "0.8")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.MoraleBroken", "0.6")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.MoraleBreaking", "0.5")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.MoraleFailing", "0.3")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.MoraleLowering", "0.2")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Morale.FullMorale", "0.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Suppression.Pinned", "1.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Suppression.Suppressed", "0.8")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Suppression.UnderFire", "0.4")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Suppression.Unsuppressed", "0.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Experience.Elite", "0.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Experience.Veteran", "0.1")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Experience.Regular", "0.2")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Experience.Green", "0.3")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.AimingAtPlayer", "1.0")
	OFP:setAIConfigPropertyValue("DispersionAccuracy.Modifiers.Base", "1.0")
	OFP:setAIConfigPropertyValue("ROE.ReturnFireAllyDistCheck", "45")
	OFP:setAIConfigPropertyValue("ROE.ReturnFireTime", "10000")
	OFP:setAIConfigPropertyValue("Follow.DistMatchLeaderStance", "80.0")
	OFP:setAIConfigPropertyValue("Command.followsimple.coverSearchRadius", "50.0")
	OFP:setAIConfigPropertyValue("Command.followelement.coverSearchRadius", "50.0")
	OFP:setAIConfigPropertyValue("Command.followformation.coverSearchRadius", "50.0")
	OFP:setAIConfigPropertyValue("Command.assaultbuilding.moveCloserDistance", "70.0")
	OFP:setAIConfigPropertyValue("Command.mount.moveCloserDistance", "70.0")
	OFP:setAIConfigPropertyValue("Command.repair.moveCloserDistance", "70.0")
	OFP:setAIConfigPropertyValue("Command.moveto.useCoverSearchRadiusAfterMoveTo", "false")
	OFP:setAIConfigPropertyValue("Command.moveto.coverSearchRadius", "40.0")
	OFP:setAIConfigPropertyValue("Command.suppress.useCoverSearchRadiusAfterMoveTo", "true")
	OFP:setAIConfigPropertyValue("Command.suppress.coverSearchRadius", "10.0")
	OFP:setAIConfigPropertyValue("Command.Default.moveCloserDistance", "120.0")
	OFP:setAIConfigPropertyValue("Command.Default.useCoverSearchRadiusAfterMoveTo", "false")
	OFP:setAIConfigPropertyValue("Command.Default.coverSearchRadius", "40.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Vehicle.underFireThreshold", "15.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Vehicle.underFireFadePPS", "1.5")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Vehicle.underFireLimit", "40.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Vehicle.underFireBase", "10.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.underFireFadePPS", "12.5")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.underFireMax", "60.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.underFireValue", "15.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.ceilingLimitAfterSuppression", "2.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.suppressionFadePPS", "0.5")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.pinnedOffTime", "2000")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.pinnedOnTime", "12000")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.unsuppressedLimit", "4.0")
	OFP:setAIConfigPropertyValue("Bullet_Sensor.Soldier.suppressedLimit", "6.0")
	OFP:setAIConfigPropertyValue("DetectionMeter.falloffDistance", "25")
	OFP:setAIConfigPropertyValue("DetectionMeter.detectedThreshold", "7.5")
	OFP:setAIConfigPropertyValue("DetectionMeter.suspectedThreshold", "0.1")
	OFP:setAIConfigPropertyValue("DetectionMeter.maxValue", "18.75")
	OFP:setAIConfigPropertyValue("DetectionMeter.valueIncrement", "7")
	OFP:setAIConfigPropertyValue("SightSensor.Proximity.maxDist", "20")
	OFP:setAIConfigPropertyValue("SightSensor.Proximity.maxSpeed", "4.0")
	OFP:setAIConfigPropertyValue("SightSensor.Proximity.minSpeed", "2.5")
	OFP:setAIConfigPropertyValue("SightSensor.Proximity.minDist", "5")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.Thermal vision.raycastFilter", "1")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.Thermal vision.Night", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.Thermal vision.Day", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.Night vision.Night", "0.6")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.Night vision.Day", "0.8")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.No filter.Night", "0.35")
	OFP:setAIConfigPropertyValue("SightSensor.Enhancement Modifiers.No filter.Day", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Equipment Modifiers.Optical x10.peripheralAngleModifier", "0.0")
	OFP:setAIConfigPropertyValue("SightSensor.Equipment Modifiers.Optical x10.peripheralRangeModifier", "0.0")
	OFP:setAIConfigPropertyValue("SightSensor.Equipment Modifiers.Optical x10.centralAngleModifier", "0.5")
	OFP:setAIConfigPropertyValue("SightSensor.Equipment Modifiers.Optical x10.centralRangeModifier", "3.5")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Unbuttoned.centralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Unbuttoned.centralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Unbuttoned.peripheralAngleModifier", "0.6")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Unbuttoned.peripheralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Unbuttoned.centralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Unbuttoned.centralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Unbuttoned.peripheralAngleModifier", "0.6")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Unbuttoned.peripheralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Unbuttoned.centralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Unbuttoned.centralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Unbuttoned.peripheralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Unbuttoned.peripheralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Buttoned.centralAngleModifier", "0.25")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Buttoned.centralRangeModifier", "4.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Buttoned.peripheralAngleModifier", "0.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Gunner Buttoned.peripheralRangeModifier", "0.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Buttoned.centralAngleModifier", "0.5")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Buttoned.centralRangeModifier", "0.65")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Buttoned.peripheralAngleModifier", "0.25")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Driver Buttoned.peripheralRangeModifier", "0.65")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Buttoned.centralAngleModifier", "0.5")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Buttoned.centralRangeModifier", "2.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Buttoned.peripheralAngleModifier", "0.25")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.Commander Buttoned.peripheralRangeModifier", "0.25")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.No modifier.centralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.No modifier.centralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.No modifier.peripheralAngleModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.Crew Modifiers.No modifier.peripheralRangeModifier", "1.0")
	OFP:setAIConfigPropertyValue("SightSensor.outOfCombatReduction", "0.31")
	OFP:setAIConfigPropertyValue("SightSensor.p_centralVisionAngle", "0.785398163")
	OFP:setAIConfigPropertyValue("SightSensor.p_peripheralVisionAngle", "1.74532925")
	OFP:setAIConfigPropertyValue("SightSensor.p_centralVisionDistance", "250")
	OFP:setAIConfigPropertyValue("SightSensor.p_peripheralVisionDistance", "125")
	OFP:setAIConfigPropertyValue("SightSensor.centralVisionAngle", "0.785398163")
	OFP:setAIConfigPropertyValue("SightSensor.peripheralVisionAngle", "1.74532925")
	OFP:setAIConfigPropertyValue("SightSensor.centralVisionDistance", "275")
	OFP:setAIConfigPropertyValue("SightSensor.peripheralVisionDistance", "125")
	OFP:setAIConfigPropertyValue("SightSensor.baseDetectionDistance", "150")
	OFP:setAIConfigPropertyValue("SightSensor.NightStartHour", "21")
	OFP:setAIConfigPropertyValue("SightSensor.DuskStartHour", "19")
	OFP:setAIConfigPropertyValue("SightSensor.DayStartHour", "8")
	OFP:setAIConfigPropertyValue("SightSensor.DawnStartHour", "4")
	
	--OFP:showPopup("setAIConfigPropertyValue", "done")
	
	OFP:setAIWeaponUsageFireRate("mw05auto30", "Normal", "Maximum", "3000")
	OFP:setAIWeaponUsageFireRate("mw05auto30", "Normal", "Minimum", "2000")
	OFP:setAIWeaponUsageFireRate("mw04autous25", "Normal", "Maximum", "3000")
	OFP:setAIWeaponUsageFireRate("mw04autous25", "Normal", "Minimum", "2000")
	OFP:setAIWeaponUsageFireRate("mw06chin30", "Normal", "Maximum", "4000")
	OFP:setAIWeaponUsageFireRate("mw06chin30", "Normal", "Minimum", "3000")
	OFP:setAIWeaponUsageFireRate("mw02gat20", "Normal", "Maximum", "5100")
	OFP:setAIWeaponUsageFireRate("mw02gat20", "Normal", "Minimum", "4100")
	OFP:setAIWeaponUsageFireRate("mw21mk19pintle", "Normal", "Maximum", "5000")
	OFP:setAIWeaponUsageFireRate("mw21mk19pintle", "Normal", "Minimum", "2500")
	OFP:setAIWeaponUsageFireRate("mw17mk19coax", "Normal", "Maximum", "5000")
	OFP:setAIWeaponUsageFireRate("mw17mk19coax", "Normal", "Minimum", "2500")
	OFP:setAIWeaponUsageFireRate("mw20lg3pintle", "Normal", "Maximum", "5000")
	OFP:setAIWeaponUsageFireRate("mw20lg3pintle", "Normal", "Minimum", "2500")
	OFP:setAIWeaponUsageFireRate("mw03autopla25", "Normal", "Maximum", "3000")
	OFP:setAIWeaponUsageFireRate("mw03autopla25", "Normal", "Minimum", "2000")
	OFP:setAIWeaponUsageFireRate("mw03aaa25", "Normal", "Maximum", "5100")
	OFP:setAIWeaponUsageFireRate("mw03aaa25", "Normal", "Minimum", "4100")
	OFP:setAIWeaponUsageFireRate("default", "Special", "Maximum", "35000")
	OFP:setAIWeaponUsageFireRate("default", "Special", "Minimum", "25000")
	OFP:setAIWeaponUsageFireRate("default", "Fast", "Maximum", "1800")
	OFP:setAIWeaponUsageFireRate("default", "Fast", "Minimum", "800")
	OFP:setAIWeaponUsageFireRate("default", "Normal", "Maximum", "5000")
	OFP:setAIWeaponUsageFireRate("default", "Normal", "Minimum", "3000")
	OFP:setAIWeaponUsageFireRate("default", "Slow", "Maximum", "7000")
	OFP:setAIWeaponUsageFireRate("default", "Slow", "Minimum", "4000")
	
	--OFP:showPopup("setAIWeaponUsageFireRate", "done")
	
	OFP:setAIWeaponUsageBurstLength("mw05auto30", "Normal", "Maximum", "1800")
	OFP:setAIWeaponUsageBurstLength("mw05auto30", "Normal", "Minimum", "600")
	OFP:setAIWeaponUsageBurstLength("mw04autous25", "Normal", "Maximum", "1800")
	OFP:setAIWeaponUsageBurstLength("mw04autous25", "Normal", "Minimum", "600")
	OFP:setAIWeaponUsageBurstLength("mw06chin30", "Normal", "Maximum", "2000")
	OFP:setAIWeaponUsageBurstLength("mw06chin30", "Normal", "Minimum", "1000")
	OFP:setAIWeaponUsageBurstLength("mw02gat20", "Normal", "Maximum", "4000")
	OFP:setAIWeaponUsageBurstLength("mw02gat20", "Normal", "Minimum", "2500")
	OFP:setAIWeaponUsageBurstLength("mw21mk19pintle", "Normal", "Maximum", "1200")
	OFP:setAIWeaponUsageBurstLength("mw21mk19pintle", "Normal", "Minimum", "300")
	OFP:setAIWeaponUsageBurstLength("mw17mk19coax", "Normal", "Maximum", "1200")
	OFP:setAIWeaponUsageBurstLength("mw17mk19coax", "Normal", "Minimum", "300")
	OFP:setAIWeaponUsageBurstLength("mw20lg3pintle", "Normal", "Maximum", "900")
	OFP:setAIWeaponUsageBurstLength("mw20lg3pintle", "Normal", "Minimum", "300")
	OFP:setAIWeaponUsageBurstLength("mw03autopla25", "Normal", "Maximum", "1800")
	OFP:setAIWeaponUsageBurstLength("mw03autopla25", "Normal", "Minimum", "600")
	OFP:setAIWeaponUsageBurstLength("mw03aaa25", "Normal", "Maximum", "4000")
	OFP:setAIWeaponUsageBurstLength("mw03aaa25", "Normal", "Minimum", "2500")
	OFP:setAIWeaponUsageBurstLength("default", "Long", "Maximum", "5000")
	OFP:setAIWeaponUsageBurstLength("default", "Long", "Minimum", "4000")
	OFP:setAIWeaponUsageBurstLength("default", "Normal", "Maximum", "3600")
	OFP:setAIWeaponUsageBurstLength("default", "Normal", "Minimum", "2400")
	OFP:setAIWeaponUsageBurstLength("default", "Short", "Maximum", "1400")
	OFP:setAIWeaponUsageBurstLength("default", "Short", "Minimum", "800")
	
	--OFP:showPopup("setAIWeaponUsageBurstLength", "done")
	
	OFP:setAIWeaponUsageDispersionRadius("default", "SnapShot", "0.95")
	OFP:setAIWeaponUsageDispersionRadius("default", "NormalShot", "0.4")
	OFP:setAIWeaponUsageDispersionRadius("default", "AimedShot", "0.13")
	
	--OFP:showPopup("setAIWeaponUsageDispersionRadius", "done")
	
	OFP:setAIDispersionSystemPropertyValue("SHOW_DEBUG", "0.0")
	OFP:setAIDispersionSystemPropertyValue("AI_MAX_AIM_OFFSET_ANGLE", "7.0f")
	OFP:setAIDispersionSystemPropertyValue("AI_MIN_GROUPING", "0.7f")
	OFP:setAIDispersionSystemPropertyValue("AI_DR_BLOCK_PLAYER_FT_MOD", "0.8")
	OFP:setAIDispersionSystemPropertyValue("AI_DR_BLOCK_SCALE_FACTOR", "0.5")
	OFP:setAIDispersionSystemPropertyValue("AI_DR_BLOCK_RADIUS", "1.4")
	OFP:setAIDispersionSystemPropertyValue("AI_DR_BLOCK_MIN_RANGE_OUTER", "35.0")
	OFP:setAIDispersionSystemPropertyValue("AI_DR_BLOCK_MIN_RANGE_INNER", "5.0")
	OFP:setAIDispersionSystemPropertyValue("AI_AIMING_PLAYER_MODIFIER", "0.0")
	OFP:setAIDispersionSystemPropertyValue("ELEVATION_HANDLING_SCALE", "0.05")
	OFP:setAIDispersionSystemPropertyValue("TURN_HANDLING_SCALE", "0.5")
	OFP:setAIDispersionSystemPropertyValue("GLOBAL_HANDLING_SCALE", "1.0")
	OFP:setAIDispersionSystemPropertyValue("MAX_RECOIL_RATIO", "5.0")
	OFP:setAIDispersionSystemPropertyValue("MAX_TO_BASE_RATIO", "30.0")
	OFP:setAIDispersionSystemPropertyValue("STANCE_PRONE_DEGREDATION", "0.5")
	OFP:setAIDispersionSystemPropertyValue("STANCE_PRONE_IMPROVEMENT", "1.5")
	OFP:setAIDispersionSystemPropertyValue("STANCE_PRONE_MODIFIER", "3.0")
	OFP:setAIDispersionSystemPropertyValue("STANCE_CROUCH_DEGREDATION", "0.75")
	OFP:setAIDispersionSystemPropertyValue("STANCE_CROUCH_IMPROVEMENT", "1.25")
	OFP:setAIDispersionSystemPropertyValue("STANCE_CROUCH_MODIFIER", "3.0")
	OFP:setAIDispersionSystemPropertyValue("STANCE_STAND_DEGREDATION", "1.0")
	OFP:setAIDispersionSystemPropertyValue("STANCE_STAND_IMPROVEMENT", "1.0")
	OFP:setAIDispersionSystemPropertyValue("STANCE_STAND_MODIFIER", "3.0")
	OFP:setAIDispersionSystemPropertyValue("FATIGUE_MODIFIER", "1.0")
	OFP:setAIDispersionSystemPropertyValue("FATIGUE_THRESHOLD", "1.0")
	OFP:setAIDispersionSystemPropertyValue("UNAIMED_MODIFIER", "3.0")
	OFP:setAIDispersionSystemPropertyValue("AIMED_MODIFIER", "0.7")
	OFP:setAIDispersionSystemPropertyValue("SPEED_JOGGING_MODIFIER", "1.5")
	OFP:setAIDispersionSystemPropertyValue("SPEED_WALKING_MODIFIER", "1.2")
	OFP:setAIDispersionSystemPropertyValue("SPEED_SHUFFLE_MODIFIER", "1.1")
	OFP:setAIDispersionSystemPropertyValue("SPEED_IDLE_MODIFIER", "1.0")
	OFP:setAIDispersionSystemPropertyValue("INJURY_MAJOR_AIM_LOSS", "1.9")
	OFP:setAIDispersionSystemPropertyValue("INJURY_MINOR_AIM_LOSS", "1.3")
	OFP:setAIDispersionSystemPropertyValue("SKILL_IMPROVEMENT_EXPERT_FACTOR", "0.3")
	OFP:setAIDispersionSystemPropertyValue("SKILL_IMPROVEMENT_ADVANCED_FACTOR", "0.5")
	OFP:setAIDispersionSystemPropertyValue("SKILL_IMPROVEMENT_BASIC_FACTOR", "0.8")
	OFP:setAIDispersionSystemPropertyValue("SKILL_IMPROVEMENT_UNTRAINED_FACTOR", "1.0")
	OFP:setAIDispersionSystemPropertyValue("SKILL_GRADE_EXPERT_FACTOR", "1.0")
	OFP:setAIDispersionSystemPropertyValue("SKILL_GRADE_ADVANCED_FACTOR", "1.0")
	OFP:setAIDispersionSystemPropertyValue("SKILL_GRADE_BASIC_FACTOR", "1.0")
	OFP:setAIDispersionSystemPropertyValue("SKILL_GRADE_UNTRAINED_FACTOR", "1.0")
	OFP:setAIDispersionSystemPropertyValue("BASE_IMPROVEMENT", "0.25")
	OFP:setAIDispersionSystemPropertyValue("BASE_DISPERSION_MODIFIER", "1.0")
	
	--OFP:showPopup("setAIDispersionSystemPropertyValue", "done")
	
	OFP:setAIDispersionSystemDRBlock("WEAPON_TYPE_SNIPER_RIFLE", 50.0, 0.0, 4, 20, 30.0, 25.0, 0.0, 4, 10)
	OFP:setAIDispersionSystemDRBlock("WEAPON_TYPE_MACHINE_GUN", 50.0, 0.0, 4, 20, 40.0, 25.0, 0.0, 4, 10)
	OFP:setAIDispersionSystemDRBlock("WEAPON_TYPE_ASSAULT_RIFLE", 50.0, 0.0, 4, 20, 40.0, 25.0, 0.0, 4, 10)
	OFP:setAIDispersionSystemDRBlock("WEAPON_TYPE_SUBMACHINE_GUN", 50.0, 0.0, 4, 20, 40.0, 25.0, 0.0, 4, 10)
	
	--OFP:showPopup("setAIDispersionSystemDRBlock", "done")
	
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_SHOULDER_LAUNCHED_JAV", "vsAI", 0.2, 120, 0.6, 1.8, 6, 18)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_SHOULDER_LAUNCHED_JAV", "vsPlayer", 0.2, 120, 0.6, 1.8, 6, 18)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_SHOULDER_LAUNCHED_GENERAL", "vsAI", 0.2, 120, 0.6, 1.8, 6, 18)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_SHOULDER_LAUNCHED_GENERAL", "vsPlayer", 0.2, 120, 0.6, 1.8, 6, 18)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_ROCKET_POD", "vsAI", 1.0, 360, 0.9, 2.0, 1, 19)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_ROCKET_POD", "vsPlayer", 1.0, 360, 0.9, 2.0, 8, 17)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_AUTOCANNON", "vsHelicopter", 1.0, 360, 1.5, 7.5, 1, 19)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_AUTOCANNON", "vsAI", 1.0, 160, 1, 2, 1, 19)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_AUTOCANNON", "vsPlayer", 1.0, 120, 1, 2, 8, 17)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_CHAIN_GUN", "vsHelicopter", 1.0, 360, 1, 5, 1, 19)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_CHAIN_GUN", "vsAI", 1.0, 160, 0.9, 3.6, 1, 19)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_CHAIN_GUN", "vsPlayer", 1.0, 120, 0.9, 3.6, 8, 17)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_MOUNTED_GREN_LAUNCHER", "vsAI", 0.1, 160, 0.5, 2, 2, 13)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_MOUNTED_GREN_LAUNCHER", "vsPlayer", 0.1, 120, 1, 3, 3, 17)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_GRENADE_LAUNCHER", "vsAI", 0.1, 120, 0.5, 2, 2, 13)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_GRENADE_LAUNCHER", "vsPlayer", 0.1, 90, 1, 3, 3, 17)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_TANK_CANNON", "vsAI", 0.2, 160, 0, 1.15, 3, 7)
	OFP:setAIDispersionSystemAimOffset("WEAPON_TYPE_TANK_CANNON", "vsPlayer", 0.2, 160, 0, 1.15, 5, 10)
	
	--OFP:showPopup("setAIDispersionSystemAimOffset", "done")
	
	--OFP:showPopup("all", "done")
	REGISTERED = true
end